apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nz01c70rd-go 
  janus-idp.io/tekton: nz01c70rd-go
  backstage.io/kubernetes-id: nz01c70rd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nz01c70rd-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  