apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nz01c70rd-go
  janus-idp.io/tekton: nz01c70rd-go
  backstage.io/kubernetes-id: nz01c70rd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nz01c70rd-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
